# Generated by Django 6.0.2 on 2026-02-28 01:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Borrado')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('imagen_url', models.URLField(blank=True, null=True, verbose_name='URL de imagen')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(limit_choices_to={'rol': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DiaRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Borrado')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='rutinas.rutina')),
            ],
            options={
                'verbose_name': 'Día de rutina',
                'verbose_name_plural': 'Días de rutina',
                'ordering': ['orden', 'dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Borrado')),
                ('ejercicio_id', models.CharField(db_index=True, max_length=64, verbose_name='ID ejercicio (microservicio)')),
                ('series', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Series')),
                ('repeticiones', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Repeticiones')),
                ('tipo_carga', models.CharField(choices=[('absoluto', 'Peso absoluto (lbs)'), ('por_disco', 'Por disco (lbs por lado)')], default='absoluto', help_text='Absoluto: peso total en lbs. Por disco: lbs cargados en cada lado de la barra.', max_length=10, verbose_name='Tipo de carga')),
                ('peso_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (lbs)')),
                ('usar_peso_corporal', models.BooleanField(default=False, verbose_name='Peso corporal')),
                ('descanso_segundos', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descanso (seg)')),
                ('tempo', models.CharField(blank=True, help_text='Formato excéntrico-pausa-concéntrico, ej: "3-1-1".', max_length=20, verbose_name='Tempo')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='rutinas.diarutina')),
            ],
            options={
                'verbose_name': 'Ejercicio de rutina',
                'verbose_name_plural': 'Ejercicios de rutina',
                'ordering': ['orden'],
                'indexes': [models.Index(fields=['ejercicio_id'], name='idx_ejercicio_ext_id')],
            },
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(fields=['cliente', 'activa'], name='idx_rutina_cliente_activa'),
        ),
    ]
