# Generated by Django 6.0.2 on 2026-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarutina',
            options={'ordering': ['orden'], 'verbose_name': 'Día de rutina', 'verbose_name_plural': 'Días de rutina'},
        ),
        migrations.RemoveField(
            model_name='diarutina',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='diarutina',
            name='dias_semana',
            field=models.CharField(blank=True, help_text='Ej: 1,3,5', max_length=50, verbose_name='Días asignados'),
        ),
        migrations.AddField(
            model_name='diarutina',
            name='nombre_bloque',
            field=models.CharField(default='Nuevo Bloque', max_length=100, verbose_name='Nombre del bloque'),
        ),
    ]
