# Generated by Django 6.0.2 on 2026-02-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_alter_diarutina_options_remove_diarutina_dia_semana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarutina',
            name='dias_semana',
        ),
        migrations.RemoveField(
            model_name='diarutina',
            name='nombre_bloque',
        ),
        migrations.AddField(
            model_name='diarutina',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], default=1, verbose_name='Día de la semana'),
            preserve_default=False,
        ),
    ]
