# Generated by Django 6.0.2 on 2026-02-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_remove_diarutina_dias_semana_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diarutina',
            unique_together={('rutina', 'dia_semana')},
        ),
    ]
