# Generated by Django 6.0.2 on 2026-02-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_alter_diarutina_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarutina',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del bloque'),
        ),
    ]
