# Generated by Django 6.0.2 on 2026-02-28 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Borrado')),
                ('nombre', models.CharField(choices=[('basica', 'Básica'), ('pro', 'Pro'), ('max', 'Max')], max_length=10, unique=True, verbose_name='Plan')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio mensual (MXN)')),
                ('duracion_dias', models.PositiveIntegerField(default=30, verbose_name='Duración (días)')),
                ('acceso_clases_grupales', models.BooleanField(default=False, verbose_name='Clases grupales')),
                ('acceso_areas_premium', models.BooleanField(default=False, verbose_name='Áreas premium')),
                ('acceso_nutricionista', models.BooleanField(default=False, verbose_name='Nutricionista')),
                ('numero_acompanantes', models.PositiveSmallIntegerField(default=0, verbose_name='Acompañantes')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de membresía',
                'verbose_name_plural': 'Tipos de membresía',
                'ordering': ['precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Borrado')),
                ('peso_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (lbs)')),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Perfil de cliente',
                'verbose_name_plural': 'Perfiles de clientes',
            },
        ),
        migrations.CreateModel(
            name='MembresiaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Borrado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio pagado (MXN)')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], default='efectivo', max_length=15, verbose_name='Método de pago')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('suspendida', 'Suspendida')], default='activa', max_length=12, verbose_name='Estado')),
                ('auto_renovar', models.BooleanField(default=False, verbose_name='Auto-renovar')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, limit_choices_to={'rol': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('usuario', models.ForeignKey(limit_choices_to={'rol': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrataciones', to='clientes.tipomembresia', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Membresía de cliente',
                'verbose_name_plural': 'Membresías de clientes',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='idx_mem_usuario_estado'), models.Index(fields=['tipo', 'estado'], name='idx_mem_tipo_estado'), models.Index(fields=['fecha_inicio'], name='idx_mem_fecha_inicio'), models.Index(fields=['fecha_fin'], name='idx_mem_fecha_fin')],
            },
        ),
    ]
