# Generated by Django 6.0.2 on 2026-02-28 03:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMedidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Borrado')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('peso_lbs', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (lbs)')),
                ('cuello', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cuello (cm)')),
                ('hombros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hombros (cm)')),
                ('pecho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pecho (cm)')),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cintura (cm)')),
                ('cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cadera (cm)')),
                ('brazo_izq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Brazo Izq (cm)')),
                ('brazo_der', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Brazo Der (cm)')),
                ('muslo_izq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Muslo Izq (cm)')),
                ('muslo_der', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Muslo Der (cm)')),
                ('pantorrilla_izq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pantorrilla Izq (cm)')),
                ('pantorrilla_der', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pantorrilla Der (cm)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_medidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de medidas',
                'verbose_name_plural': 'Registros de medidas',
                'ordering': ['-fecha'],
            },
        ),
    ]
