# Generated by Django 6.0.2 on 2026-03-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_registromedidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromedidas',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC'),
        ),
        migrations.AddField(
            model_name='registromedidas',
            name='porcentaje_grasa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Grasa'),
        ),
    ]
